### ISSUE TITLE
plugin is not supported for mp4 and turbo

### ISSUE THREAD

**Issue by CodyNinja1** [dwhitacre/openplanet-snake#1]
you can fix this by adding them as supported games in the openplanet admin panel

**Comment by dwhitacre** [comment]
@CodyNinja1 I didn't try to add explicit support for these nor do I plan to test them. Should I enable it anyways?

**Comment by dwhitacre** [comment]
![image](https://github.com/dwhitacre/openplanet-snake/assets/13386624/7abf3585-2aeb-4914-861c-4f65c058d6bb)

**Comment by ezio416** [comment]
it seems to work fine on mp4 and turbo, just need to enable support like you show above so it can be installed in the plugin manager

**Comment by dwhitacre** [comment]
![image](https://github.com/dwhitacre/openplanet-snake/assets/13386624/20454517-1990-4088-a8a0-aa30d4a976e1)
ok added, i offer no support for these, I am open to PRs to make them work if issues are found. good luck
