### ISSUE TITLE
allow setting play region

### ISSUE THREAD

**Issue by ezio416** [dwhitacre/openplanet-snake#2]
It would be nice so be able to set a region in which the game happens instead of the full screen so things don't get hidden (behind the Openplanet menu bar in my case). Also maybe with a border around it

**Comment by dwhitacre** [comment]
added a border for 1.2.0, changing the play area will take a bit more work to calculate how that affects grid size and spawning of apple/snake. should be straight forward but not going to get to it tonight probably. maybe later this week

**Comment by dwhitacre** [comment]
rudimentary approach that letsthe grid start and end at arbitrary offsets
https://github.com/dwhitacre/openplanet-snake/pull/4

this leads to the grid ending up not center most of the time though unless your aspect ratio of cell counts happens to match well w/ your resolution aspect ratio

dont love this solution, will likely try to find some middle ground in what i had before (which was friendly to dynamic resolutions) and this

**Comment by dwhitacre** [comment]
ah was being dumb, fixed the ratio issue and this better grid works fine now
